-- ------------------------------------------------------------
-- Trendiv Database Schema (Supabase)
-- ------------------------------------------------------------

-- 1. Trend 테이블 확장 (Category 추가)
-- 기존에 테이블이 있다면 컬럼만 추가합니다.
ALTER TABLE trend 
ADD COLUMN IF NOT EXISTS category text;

-- 2. 성능 최적화를 위한 인덱스 (검색 속도 향상)
-- source(출처)와 category(플랫폼)로 자주 필터링하므로 인덱스 필수
CREATE INDEX IF NOT EXISTS idx_trend_source ON trend(source);
CREATE INDEX IF NOT EXISTS idx_trend_category ON trend(category);

-- 3. (참고) Trend 테이블 기본 스키마
-- create table public.trend (
--   id bigint generated by default as identity,
--   created_at timestamp with time zone not null default now(),
--   title text null,
--   link text not null,
--   date text null,
--   source text null,
--   status text null default 'RAW'::text,
--   analysis_results jsonb[] null,
--   category text null, -- 위에 추가된 컬럼
--   constraint trend_pkey primary key (id),
--   constraint trend_link_key unique (link)
-- ) tablespace pg_default;